# Import Libraries

In [4]:
import pandas as pd
import numpy as np

# Load Dataset

In [5]:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
df = pd.read_csv("ml-100k/u.data", sep='\t', names=r_cols, encoding='latin-1')

In [6]:
df

user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

# Get Unique users

In [6]:
n_users = df.user_id.unique().shape[0]

In [7]:
n_users

943

# Create pivot table for user and movie based on ratings

In [8]:
data_matrix = df.pivot_table(index='user_id', columns= 'movie_id', values='rating')

In [9]:
data_matrix

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5          4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940        NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941        5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943        NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943        NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

# Replace null values with 0

In [10]:
data_matrix.replace(np.nan, 0, inplace=True)

In [11]:
data_matrix

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
940        0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   3.0   0.0  ...   
941        5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
942        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
943        0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
943        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

# Find Cosine Similatity for user

In [12]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(data_matrix, metric='cosine')

In [13]:
user_similarity

array([[1.33226763e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 0.00000000e+00, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 0.00000000e+00, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

# prediction table

In [14]:
data_matrix

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2          4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
5          4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
940        0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   3.0   0.0  ...   
941        5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
942        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
943        0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   

movie_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                               
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
943        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [15]:
type(data_matrix.mean(axis=1))

pandas.core.series.Series

In [16]:
data_matrix.mean(axis=1)

user_id
1      0.583829
2      0.136742
3      0.089774
4      0.061831
5      0.299049
         ...   
939    0.124257
940    0.219976
941    0.052913
942    0.200357
943    0.340666
Length: 943, dtype: float64

In [17]:
mean_user_rating = data_matrix.mean(axis=1).to_numpy()

In [18]:
mean_user_rating

array([0.58382878, 0.13674197, 0.08977408, 0.06183115, 0.29904875,
       0.45600476, 0.95005945, 0.13317479, 0.05588585, 0.46016647,
       0.37277051, 0.13317479, 1.17122473, 0.23840666, 0.17776457,
       0.36028537, 0.05053508, 0.6391201 , 0.04221165, 0.08858502,
       0.28418549, 0.25505351, 0.32639715, 0.17479191, 0.18787158,
       0.18727705, 0.04815696, 0.17479191, 0.07372176, 0.09631391,
       0.08382878, 0.08085612, 0.0529132 , 0.04815696, 0.04458977,
       0.0451843 , 0.12366231, 0.26753864, 0.04934602, 0.06004756,
       0.11652794, 0.40546968, 0.48751486, 0.32758621, 0.10285375,
       0.06599287, 0.05410226, 0.14863258, 0.343044  , 0.05053508,
       0.04875149, 0.14209275, 0.06361474, 0.14268728, 0.04102259,
       0.40487515, 0.22057075, 0.35136742, 0.89357907, 0.50535077,
       0.03686088, 0.45541023, 0.17241379, 0.42627824, 0.18727705,
       0.078478  , 0.06718193, 0.06123662, 0.14863258, 0.26991677,
       0.08561237, 0.31093936, 0.14625446, 0.08442331, 0.15398

In [19]:
mean_user_rating[:, np.newaxis]

array([[0.58382878],
       [0.13674197],
       [0.08977408],
       [0.06183115],
       [0.29904875],
       [0.45600476],
       [0.95005945],
       [0.13317479],
       [0.05588585],
       [0.46016647],
       [0.37277051],
       [0.13317479],
       [1.17122473],
       [0.23840666],
       [0.17776457],
       [0.36028537],
       [0.05053508],
       [0.6391201 ],
       [0.04221165],
       [0.08858502],
       [0.28418549],
       [0.25505351],
       [0.32639715],
       [0.17479191],
       [0.18787158],
       [0.18727705],
       [0.04815696],
       [0.17479191],
       [0.07372176],
       [0.09631391],
       [0.08382878],
       [0.08085612],
       [0.0529132 ],
       [0.04815696],
       [0.04458977],
       [0.0451843 ],
       [0.12366231],
       [0.26753864],
       [0.04934602],
       [0.06004756],
       [0.11652794],
       [0.40546968],
       [0.48751486],
       [0.32758621],
       [0.10285375],
       [0.06599287],
       [0.05410226],
       [0.148

In [20]:
ratings_diff = (data_matrix - mean_user_rating[:, np.newaxis])

In [21]:
ratings_diff

movie_id      1         2         3         4         5         6     \
user_id                                                                
1         4.416171  2.416171  3.416171  2.416171  2.416171  4.416171   
2         3.863258 -0.136742 -0.136742 -0.136742 -0.136742 -0.136742   
3        -0.089774 -0.089774 -0.089774 -0.089774 -0.089774 -0.089774   
4        -0.061831 -0.061831 -0.061831 -0.061831 -0.061831 -0.061831   
5         3.700951  2.700951 -0.299049 -0.299049 -0.299049 -0.299049   
...            ...       ...       ...       ...       ...       ...   
939      -0.124257 -0.124257 -0.124257 -0.124257 -0.124257 -0.124257   
940      -0.219976 -0.219976 -0.219976  1.780024 -0.219976 -0.219976   
941       4.947087 -0.052913 -0.052913 -0.052913 -0.052913 -0.052913   
942      -0.200357 -0.200357 -0.200357 -0.200357 -0.200357 -0.200357   
943      -0.340666  4.659334 -0.340666 -0.340666 -0.340666 -0.340666   

movie_id      7         8         9         10    ...      1673      1674  \
user_id                                           ...                       
1         3.416171  0.416171  4.416171  2.416171  ... -0.583829 -0.583829   
2        -0.136742 -0.136742 -0.136742  1.863258  ... -0.136742 -0.136742   
3        -0.089774 -0.089774 -0.089774 -0.089774  ... -0.089774 -0.089774   
4        -0.061831 -0.061831 -0.061831 -0.061831  ... -0.061831 -0.061831   
5        -0.299049 -0.299049 -0.299049 -0.299049  ... -0.299049 -0.299049   
...            ...       ...       ...       ...  ...       ...       ...   
939      -0.124257 -0.124257  4.875743 -0.124257  ... -0.124257 -0.124257   
940       3.780024  4.780024  2.780024 -0.219976  ... -0.219976 -0.219976   
941       3.947087 -0.052913 -0.052913 -0.052913  ... -0.052913 -0.052913   
942      -0.200357 -0.200357 -0.200357 -0.200357  ... -0.200357 -0.200357   
943      -0.340666 -0.340666  2.659334 -0.340666  ... -0.340666 -0.340666   

movie_id      1675      1676      1677      1678      1679      1680  \
user_id                                                                
1        -0.583829 -0.583829 -0.583829 -0.583829 -0.583829 -0.583829   
2        -0.136742 -0.136742 -0.136742 -0.136742 -0.136742 -0.136742   
3        -0.089774 -0.089774 -0.089774 -0.089774 -0.089774 -0.089774   
4        -0.061831 -0.061831 -0.061831 -0.061831 -0.061831 -0.061831   
5        -0.299049 -0.299049 -0.299049 -0.299049 -0.299049 -0.299049   
...            ...       ...       ...       ...       ...       ...   
939      -0.124257 -0.124257 -0.124257 -0.124257 -0.124257 -0.124257   
940      -0.219976 -0.219976 -0.219976 -0.219976 -0.219976 -0.219976   
941      -0.052913 -0.052913 -0.052913 -0.052913 -0.052913 -0.052913   
942      -0.200357 -0.200357 -0.200357 -0.200357 -0.200357 -0.200357   
943      -0.340666 -0.340666 -0.340666 -0.340666 -0.340666 -0.340666   

movie_id      1681      1682  
user_id                       
1        -0.583829 -0.583829  
2        -0.136742 -0.136742  
3        -0.089774 -0.089774  
4        -0.061831 -0.061831  
5        -0.299049 -0.299049  
...            ...       ...  
939      -0.124257 -0.124257  
940      -0.219976 -0.219976  
941      -0.052913 -0.052913  
942      -0.200357 -0.200357  
943      -0.340666 -0.340666  

[943 rows x 1682 columns]

In [22]:
user_similarity.dot(ratings_diff)

array([[1053.46456048,  106.99918332,   32.77730441, ..., -135.27488255,
        -135.66005564, -135.85741105],
       [1236.14249108,  187.96477188,   45.1764139 , ..., -171.10760287,
        -169.99820267, -169.8412708 ],
       [1409.18485925,  197.62870362,   57.03606449, ..., -187.29854641,
        -185.62705133, -185.45885449],
       ...,
       [1245.81782545,  180.04311388,   39.90412677, ..., -178.35011786,
        -177.72089084, -177.5907325 ],
       [1258.24647345,  159.77486735,   58.68675582, ..., -163.6732682 ,
        -163.19833111, -162.87221498],
       [1128.30290113,  104.69887603,   33.37003481, ..., -145.99356249,
        -146.42195908, -146.33422024]])

In [23]:
np.abs(user_similarity)

array([[1.33226763e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 0.00000000e+00, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 0.00000000e+00, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

In [24]:
np.abs(user_similarity).sum(axis=1)

array([711.08099519, 760.07331717, 825.95402725, 827.39224279,
       779.66510396, 716.76574749, 713.40474397, 777.18367345,
       844.95785479, 738.25941741, 759.6083914 , 787.5837141 ,
       689.77352349, 749.23289325, 767.9488538 , 730.66594402,
       794.99966418, 725.35033113, 838.87922505, 790.62608759,
       787.57614319, 770.40422666, 737.33790467, 753.67929565,
       762.77562448, 711.92729357, 830.83431315, 766.29113247,
       817.83967763, 790.00049674, 867.79453678, 776.19443727,
       821.53541302, 876.69262601, 850.58533255, 879.44009825,
       793.09362316, 813.0746822 , 811.56933214, 820.51863065,
       771.41748237, 735.21753652, 688.87865937, 712.25901375,
       795.12865583, 789.45396034, 827.92760469, 786.45655402,
       781.28197329, 858.78586253, 828.78338027, 786.99216242,
       792.56008095, 746.92036575, 809.75085538, 725.44741742,
       740.58904277, 731.54581269, 696.33734916, 743.26197507,
       824.87190201, 701.06611664, 758.99343356, 693.76

In [25]:
np.array([np.abs(user_similarity).sum(axis=1)]).T

array([[711.08099519],
       [760.07331717],
       [825.95402725],
       [827.39224279],
       [779.66510396],
       [716.76574749],
       [713.40474397],
       [777.18367345],
       [844.95785479],
       [738.25941741],
       [759.6083914 ],
       [787.5837141 ],
       [689.77352349],
       [749.23289325],
       [767.9488538 ],
       [730.66594402],
       [794.99966418],
       [725.35033113],
       [838.87922505],
       [790.62608759],
       [787.57614319],
       [770.40422666],
       [737.33790467],
       [753.67929565],
       [762.77562448],
       [711.92729357],
       [830.83431315],
       [766.29113247],
       [817.83967763],
       [790.00049674],
       [867.79453678],
       [776.19443727],
       [821.53541302],
       [876.69262601],
       [850.58533255],
       [879.44009825],
       [793.09362316],
       [813.0746822 ],
       [811.56933214],
       [820.51863065],
       [771.41748237],
       [735.21753652],
       [688.87865937],
       [712

In [26]:
def predict(data_matrix, similarity, type):
    if type=='user':
        mean_user_rating = data_matrix.mean(axis=1).to_numpy()
        ratings_diff = (data_matrix - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    return pred
        

In [27]:
user_prediction = predict(data_matrix, user_similarity, type='user')

In [28]:
user_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]])

### As per User based filtering ,first have to find similarity between the input user and others

In [29]:
input_user = 34

In [32]:
user_sim_table=pd.DataFrame(user_similarity)

In [33]:
user_sim_table

0         1         2         3         4         5         6    \
0    1.332268e-15  0.833069  0.952540  0.935642  0.621525  0.569761  0.559633   
1    8.330690e-01  0.000000  0.889409  0.821879  0.927021  0.754157  0.892672   
2    9.525405e-01  0.889409  0.000000  0.655849  0.978755  0.927585  0.933863   
3    9.356422e-01  0.821879  0.655849  0.000000  0.968196  0.931956  0.908770   
4    6.215248e-01  0.927021  0.978755  0.968196  0.000000  0.762714  0.626400   
..            ...       ...       ...       ...       ...       ...       ...   
938  8.819047e-01  0.771417  0.973729  0.969862  0.928541  0.888148  0.892973   
939  6.859280e-01  0.773210  0.838110  0.803142  0.760045  0.647551  0.670075   
940  8.513831e-01  0.838515  0.898757  0.847959  0.860405  0.855554  0.940007   
941  8.204921e-01  0.827732  0.866584  0.829914  0.847503  0.682672  0.717997   
942  6.018253e-01  0.894202  0.973444  0.941248  0.686059  0.723958  0.605636   

          7         8         9    ...       933       934       935  \
0    0.680928  0.921862  0.623456  ...  0.630473  0.880518  0.725124   
1    0.896656  0.838952  0.840138  ...  0.843014  0.692058  0.641211   
2    0.916940  0.938960  0.934849  ...  0.968125  0.957247  0.836171   
3    0.811940  0.898716  0.939141  ...  0.947893  0.963216  0.866885   
4    0.751070  0.943153  0.798573  ...  0.661206  0.919420  0.905076   
..        ...       ...       ...  ...       ...       ...       ...   
938  0.904102  0.960148  0.928540  ...  0.933961  0.568846  0.741979   
939  0.753117  0.879505  0.657039  ...  0.672847  0.892976  0.812464   
940  0.853855  0.856755  0.909695  ...  0.953048  0.796699  0.711682   
941  0.824678  0.907503  0.787670  ...  0.773560  0.926487  0.910412   
942  0.700191  0.924383  0.778140  ...  0.736209  0.789237  0.856747   

          936       937       938       939       940       941       942  
0    0.810295  0.802674  0.881905  0.685928  0.851383  0.820492  0.601825  
1    0.575954  0.680111  0.771417  0.773210  0.838515  0.827732  0.894202  
2    0.930962  0.875755  0.973729  0.838110  0.898757  0.866584  0.973444  
3    0.806529  0.853942  0.969862  0.803142  0.847959  0.829914  0.941248  
4    0.920221  0.851393  0.928541  0.760045  0.860405  0.847503  0.686059  
..        ...       ...       ...       ...       ...       ...       ...  
938  0.773551  0.567334  0.000000  0.912313  0.819971  0.956736  0.855750  
939  0.818683  0.824842  0.912313  0.000000  0.854848  0.738624  0.758972  
940  0.765789  0.686600  0.819971  0.854848  0.000000  0.898358  0.904880  
941  0.870446  0.900615  0.956736  0.738624  0.898358  0.000000  0.817535  
942  0.922207  0.797756  0.855750  0.758972  0.904880  0.817535  0.000000  

[943 rows x 943 columns]

In [38]:
similar_input_user= user_sim_table[input_user].sort_values(ascending=True).head(5).index

In [39]:
similar_input_user

Index([34, 450, 852, 811, 509], dtype='int64')

In [37]:
user_sim_table[input_user].sort_values(ascending=True)

34     1.110223e-16
450    4.338511e-01
852    4.595095e-01
811    4.964443e-01
509    4.996907e-01
           ...     
776    1.000000e+00
777    1.000000e+00
613    1.000000e+00
282    1.000000e+00
942    1.000000e+00
Name: 34, Length: 943, dtype: float64

In [36]:
similar_input_user

Index([34, 450, 852, 811, 509], dtype='int64')

In [40]:
#4.Convert into a list

similar_user_input=list(similar_input_user)

In [41]:
similar_user_input

[34, 450, 852, 811, 509]

In [51]:
#5. Using similar_user_input,can select movie id from ratings table

similar_user_movieid_list=[]
for sim_user in similar_user_input:
    sim=list(df[df['user_id']==sim_user]['movie_id'])
    similar_user_movieid_list.append(sim)

In [52]:
similar_user_movieid_list

[[312,
  242,
  690,
  310,
  259,
  299,
  245,
  332,
  329,
  286,
  1024,
  324,
  294,
  292,
  990,
  289,
  898,
  899,
  288,
  991],
 [470,
  783,
  1147,
  100,
  58,
  142,
  801,
  216,
  785,
  162,
  144,
  462,
  384,
  739,
  1269,
  179,
  38,
  659,
  252,
  1160,
  566,
  496,
  679,
  387,
  908,
  265,
  1226,
  183,
  1037,
  194,
  902,
  1263,
  64,
  1036,
  942,
  467,
  1212,
  97,
  762,
  143,
  583,
  480,
  846,
  561,
  487,
  2,
  237,
  39,
  778,
  815,
  708,
  400,
  495,
  382,
  518,
  110,
  1203,
  710,
  660,
  152,
  304,
  520,
  604,
  642,
  494,
  211,
  847,
  559,
  1446,
  204,
  904,
  1092,
  281,
  526,
  139,
  200,
  367,
  553,
  523,
  685,
  478,
  177,
  742,
  1044,
  509,
  89,
  238,
  29,
  15,
  837,
  65,
  49,
  176,
  434,
  729,
  1184,
  70,
  728,
  174,
  1047,
  723,
  477,
  419,
  689,
  582,
  270,
  7,
  155,
  12,
  774,
  383,
  488,
  145,
  401,
  301,
  468,
  157,
  771,
  650,
  288,
  95,
  1,
  154,
  

In [53]:
# 6. Convert all the list as single
import itertools
similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))

In [54]:
len(similar_user_movieid_single_list)

663

In [56]:
#7. Unique movieid from the list

Unique_movieid_similar_user=set(similar_user_movieid_single_list)

In [57]:
Unique_movieid_similar_user

{1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 242,
 243,
 245,
 250,
 252,
 254,
 257,
 258,
 259,
 260,
 264,
 265,
 266,
 268,

In [58]:
#8. Input user watched movie_list

input_user_watched_movieid=list(df[df['user_id']==input_user]['movie_id'].values)

In [60]:
input_user_watched_movieid

[312,
 242,
 690,
 310,
 259,
 299,
 245,
 332,
 329,
 286,
 1024,
 324,
 294,
 292,
 990,
 289,
 898,
 899,
 288,
 991]

In [61]:
#9. Create a list which should have recom movieid to the input user

recom=[]
for per_id in Unique_movieid_similar_user:
    if(per_id in input_user_watched_movieid):
        pass
    else:
        recom.append(per_id)

In [62]:
recom

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 243,
 250,
 252,
 254,
 257,
 258,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,

In [64]:
len(recom)

570

In [65]:
sorted(recom)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 243,
 250,
 252,
 254,
 257,
 258,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,

In [66]:
# Cross Checking 
sorted(Unique_movieid_similar_user)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 242,
 243,
 245,
 250,
 252,
 254,
 257,
 258,
 259,
 260,
 264,
 265,
 266,
 268,

In [67]:
# Cross Checking
sorted(input_user_watched_movieid)

[242,
 245,
 259,
 286,
 288,
 289,
 292,
 294,
 299,
 310,
 312,
 324,
 329,
 332,
 690,
 898,
 899,
 990,
 991,
 1024]

In [68]:
# Checking the common movie list
list(set(Unique_movieid_similar_user)&set(input_user_watched_movieid))

[1024,
 898,
 259,
 899,
 286,
 288,
 289,
 292,
 294,
 299,
 690,
 310,
 312,
 324,
 329,
 332,
 990,
 991,
 242,
 245]

In [69]:
# Checking the common movie list
list(set(recom)&set(input_user_watched_movieid))

[]

In [70]:
user_pred=pd.DataFrame(user_prediction)

In [71]:
user_pred

0         1         2         3         4         5         6     \
0    2.065326  0.734303  0.629924  1.010669  0.640686  0.476150  1.784569   
1    1.763088  0.384040  0.196179  0.731538  0.225643  0.003892  1.493597   
2    1.795904  0.329047  0.158829  0.684154  0.173277 -0.035621  1.488230   
3    1.729951  0.293913  0.127741  0.644932  0.142143 -0.062261  1.437010   
4    1.796651  0.454474  0.354422  0.763130  0.359539  0.195987  1.547370   
..        ...       ...       ...       ...       ...       ...       ...   
938  1.676950  0.346339  0.177518  0.689906  0.199740  0.003297  1.429565   
939  1.822346  0.419125  0.286430  0.715605  0.294442  0.106633  1.514591   
940  1.591515  0.275269  0.102195  0.624383  0.133762 -0.069553  1.320734   
941  1.810363  0.404799  0.275450  0.726616  0.281316  0.087068  1.550310   
942  1.838431  0.479648  0.384963  0.780521  0.388442  0.240998  1.564232   

         7         8         9     ...      1672      1673      1674  \
0    1.163032  1.513350  0.704478  ...  0.394041  0.394434  0.393981   
1    0.876153  1.108467  0.261991  ... -0.086942 -0.085491 -0.087137   
2    0.835769  1.135426  0.236383  ... -0.134795 -0.133537 -0.135543   
3    0.796249  1.096663  0.211789  ... -0.161413 -0.160220 -0.161542   
4    0.908904  1.292027  0.437954  ...  0.101762  0.102405  0.101923   
..        ...       ...       ...  ...       ...       ...       ...   
938  0.830905  1.070986  0.262183  ... -0.092434 -0.091197 -0.092851   
939  0.853050  1.195304  0.359260  ...  0.014060  0.014688  0.014123   
940  0.765529  1.035088  0.192697  ... -0.166179 -0.164981 -0.166278   
941  0.850057  1.205745  0.342987  ... -0.008362 -0.007757 -0.008225   
942  0.946704  1.289865  0.487383  ...  0.147027  0.148208  0.147193   

         1675      1676      1677      1678      1679      1680      1681  
0    0.392972  0.393344  0.392272  0.394909  0.393590  0.393049  0.392771  
1   -0.088158 -0.087298 -0.089288 -0.087468 -0.088378 -0.086918 -0.086712  
2   -0.136438 -0.135041 -0.137611 -0.136374 -0.136992 -0.134969 -0.134765  
3   -0.162586 -0.161634 -0.163877 -0.162283 -0.163080 -0.161442 -0.161248  
4    0.100839  0.101711  0.099951  0.102515  0.101233  0.101075  0.101201  
..        ...       ...       ...       ...       ...       ...       ...  
938 -0.093801 -0.092953 -0.094539 -0.092217 -0.093378 -0.092686 -0.092423  
939  0.013060  0.013669  0.011978  0.014065  0.013021  0.013639  0.013796  
940 -0.167392 -0.166679 -0.168486 -0.166217 -0.167352 -0.166575 -0.166414  
941 -0.009218 -0.008232 -0.010138 -0.008009 -0.009074 -0.008466 -0.008049  
942  0.146199  0.146916  0.145539  0.148194  0.146867  0.146298  0.146415  

[943 rows x 1682 columns]

In [72]:
user_pred_Trans=user_pred.T

In [73]:
user_pred_Trans

0         1         2         3         4         5         6    \
0     2.065326  1.763088  1.795904  1.729951  1.796651  1.996889  2.466055   
1     0.734303  0.384040  0.329047  0.293913  0.454474  0.651172  1.099186   
2     0.629924  0.196179  0.158829  0.127741  0.354422  0.528276  1.016489   
3     1.010669  0.731538  0.684154  0.644932  0.763130  0.921054  1.362861   
4     0.640686  0.225643  0.173277  0.142143  0.359539  0.537388  1.006458   
...        ...       ...       ...       ...       ...       ...       ...   
1677  0.392272 -0.089288 -0.137611 -0.163877  0.099951  0.259848  0.764340   
1678  0.394909 -0.087468 -0.136374 -0.162283  0.102515  0.262375  0.766967   
1679  0.393590 -0.088378 -0.136992 -0.163080  0.101233  0.261111  0.765654   
1680  0.393049 -0.086918 -0.134969 -0.161442  0.101075  0.261061  0.764983   
1681  0.392771 -0.086712 -0.134765 -0.161248  0.101201  0.261089  0.765165   

           7         8         9    ...       933       934       935  \
0     1.693486  1.681165  2.021688  ...  1.924844  1.619096  1.891812   
1     0.296285  0.279528  0.650911  ...  0.552456  0.311680  0.550513   
2     0.195398  0.121887  0.530669  ...  0.451194  0.140613  0.354913   
3     0.612075  0.616094  0.916215  ...  0.834176  0.661829  0.893214   
4     0.198638  0.136368  0.531720  ...  0.455212  0.166992  0.398759   
...        ...       ...       ...  ...       ...       ...       ...   
1677 -0.072866 -0.163505  0.263527  ...  0.185602 -0.128949  0.095681   
1678 -0.070435 -0.161425  0.266037  ...  0.188059 -0.126624  0.097792   
1679 -0.071651 -0.162465  0.264782  ...  0.186831 -0.127786  0.096736   
1680 -0.071744 -0.161396  0.264589  ...  0.186850 -0.127045  0.097826   
1681 -0.071357 -0.161430  0.264781  ...  0.186858 -0.126812  0.097654   

           936       937       938       939       940       941       942  
0     1.696368  1.717658  1.676950  1.822346  1.591515  1.810363  1.838431  
1     0.322611  0.431368  0.346339  0.419125  0.275269  0.404799  0.479648  
2     0.144344  0.247851  0.177518  0.286430  0.102195  0.275450  0.384963  
3     0.662304  0.783208  0.689906  0.715605  0.624383  0.726616  0.780521  
4     0.167841  0.283796  0.199740  0.294442  0.133762  0.281316  0.388442  
...        ...       ...       ...       ...       ...       ...       ...  
1677 -0.143177 -0.009425 -0.094539  0.011978 -0.168486 -0.010138  0.145539  
1678 -0.141018 -0.007085 -0.092217  0.014065 -0.166217 -0.008009  0.148194  
1679 -0.142097 -0.008255 -0.093378  0.013021 -0.167352 -0.009074  0.146867  
1680 -0.140977 -0.007621 -0.092686  0.013639 -0.166575 -0.008466  0.146298  
1681 -0.140965 -0.007369 -0.092423  0.013796 -0.166414 -0.008049  0.146415  

[1682 rows x 943 columns]

In [76]:
user_pred_Trans[34]

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...   
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [77]:
gg=user_pred_Trans[34]

In [78]:
gg

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...   
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [79]:
g=pd.DataFrame(gg)

In [80]:
g

34
0     1.740469
1     0.283366
2     0.114987
3     0.645096
4     0.127844
...        ...
1677 -0.183977
1678 -0.182367
1679 -0.183172
1680 -0.181400
1681 -0.181306

[1682 rows x 1 columns]

In [81]:
s=g.T

In [82]:
s

0         1         2         3         4         5         6     \
34  1.740469  0.283366  0.114987  0.645096  0.127844 -0.081329  1.448638   

        7        8         9     ...      1672      1673      1674      1675  \
34  0.794313  1.08901  0.194232  ... -0.181256 -0.180156 -0.181837 -0.182819   

        1676      1677      1678      1679    1680      1681  
34 -0.181432 -0.183977 -0.182367 -0.183172 -0.1814 -0.181306  

[1 rows x 1682 columns]

In [83]:
s[187].values >=0.4

array([ True])

In [84]:
# From recomd list select hightest rated film which would like by the user. Based on User prediction

highest_Rated=[]
input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
input_user_pred=input_user_pre.T
for re in recom:
    value=input_user_pred[re].values
    if(value>=1):
        highest_Rated.append(re)

In [85]:
highest_Rated

[11,
 49,
 63,
 78,
 88,
 95,
 97,
 99,
 126,
 167,
 172,
 173,
 180,
 182,
 190,
 194,
 203,
 215,
 221,
 257,
 268,
 275,
 287,
 301,
 356,
 422,
 482]

In [86]:
len(highest_Rated)

27

In [87]:
# Now we give movieid respective movie list


i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,
encoding='latin-1')

In [89]:
#Creating Movie List based on recom movieid
movie_title=[]
for movieid in highest_Rated:
    mov=items[items['movie id']==movieid]['movie title'].values
    movie_title.append(mov)

In [90]:
movie_title

[array(['Seven (Se7en) (1995)'], dtype=object),
 array(['I.Q. (1994)'], dtype=object),
 array(['Santa Clause, The (1994)'], dtype=object),
 array(['Free Willy (1993)'], dtype=object),
 array(['Sleepless in Seattle (1993)'], dtype=object),
 array(['Aladdin (1992)'], dtype=object),
 array(['Dances with Wolves (1990)'], dtype=object),
 array(['Snow White and the Seven Dwarfs (1937)'], dtype=object),
 array(['Spitfire Grill, The (1996)'], dtype=object),
 array(['Private Benjamin (1980)'], dtype=object),
 array(['Empire Strikes Back, The (1980)'], dtype=object),
 array(['Princess Bride, The (1987)'], dtype=object),
 array(['Apocalypse Now (1979)'], dtype=object),
 array(['GoodFellas (1990)'], dtype=object),
 array(['Henry V (1989)'], dtype=object),
 array(['Sting, The (1973)'], dtype=object),
 array(['Unforgiven (1992)'], dtype=object),
 array(['Field of Dreams (1989)'], dtype=object),
 array(['Breaking the Waves (1996)'], dtype=object),
 array(['Men in Black (1997)'], dtype=object),
 array

In [91]:
#Converting into pure list
movie_title_list=[]
for m in movie_title:
    print(m)
    mv=list(m)
    movie_title_list.append(mv)

['Seven (Se7en) (1995)']
['I.Q. (1994)']
['Santa Clause, The (1994)']
['Free Willy (1993)']
['Sleepless in Seattle (1993)']
['Aladdin (1992)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Spitfire Grill, The (1996)']
['Private Benjamin (1980)']
['Empire Strikes Back, The (1980)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['GoodFellas (1990)']
['Henry V (1989)']
['Sting, The (1973)']
['Unforgiven (1992)']
['Field of Dreams (1989)']
['Breaking the Waves (1996)']
['Men in Black (1997)']
['Chasing Amy (1997)']
['Sense and Sensibility (1995)']
["Marvin's Room (1996)"]
['In & Out (1997)']
['Client, The (1994)']
['Aladdin and the King of Thieves (1996)']
['Some Like It Hot (1959)']


In [92]:
#Converting into whole list
import itertools
Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))

In [93]:
Final_Recommend_movie

['Seven (Se7en) (1995)',
 'I.Q. (1994)',
 'Santa Clause, The (1994)',
 'Free Willy (1993)',
 'Sleepless in Seattle (1993)',
 'Aladdin (1992)',
 'Dances with Wolves (1990)',
 'Snow White and the Seven Dwarfs (1937)',
 'Spitfire Grill, The (1996)',
 'Private Benjamin (1980)',
 'Empire Strikes Back, The (1980)',
 'Princess Bride, The (1987)',
 'Apocalypse Now (1979)',
 'GoodFellas (1990)',
 'Henry V (1989)',
 'Sting, The (1973)',
 'Unforgiven (1992)',
 'Field of Dreams (1989)',
 'Breaking the Waves (1996)',
 'Men in Black (1997)',
 'Chasing Amy (1997)',
 'Sense and Sensibility (1995)',
 "Marvin's Room (1996)",
 'In & Out (1997)',
 'Client, The (1994)',
 'Aladdin and the King of Thieves (1996)',
 'Some Like It Hot (1959)']

In [100]:
def userbased(input_user,user_similarity,user_predictions,similar_user_count,thres):
    #Convert the user_sim table into DataFrame
    user_sim_table=pd.DataFrame(user_similarity)
    #Find similarity user for 67 using cosine table
    similar_input_user= user_sim_table[input_user].sort_values(ascending=True).head(similar_user_count).index
    #Convert in to list
    similar_user_input=list(similar_input_user) 
    #Using similar_user_input,can select movie id from ratings table
    similar_user_movieid_list=[]
    for sim_user in similar_user_input:
        sim=list(df[df['user_id']==sim_user]['movie_id'])
        similar_user_movieid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))
    #Unique movieid from the list
    Unique_movieid_similar_user=set(similar_user_movieid_single_list)
    #Input user watched movie_list
    input_user_watched_movieid=list(df[df['user_id']==input_user]['movie_id'].values)
    #Create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_movieid_similar_user:
        if(per_id in input_user_watched_movieid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(user_prediction)
    user_pred_Trans=user_pred.T
    input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
    input_user_pred=input_user_pre.T
    for re in recom:
        value=input_user_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
    items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols,encoding='latin-1')
    #Creating Movie List based on recom movieid
    movie_title=[]
    for movieid in highest_Rated:
        mov=items[items['movie id']==movieid]['movie title'].values
        movie_title.append(mov)
    #Converting into pure list
    movie_title_list=[]
    for m in movie_title:
        print(m)
        mv=list(m)
        movie_title_list.append(mv)
    #Converting into whole list
    import itertools
    Final_Recommend_movie=list(itertools.chain.from_iterable(movie_title_list))
    print("The common Movie in Recom & User:",list(set(recom)&set(input_user_watched_movieid)))
    return Final_Recommend_movie
    

In [101]:
Recommended_movie=userbased(67,user_similarity,user_pred,5,1.5)

['Professional, The (1994)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['Men in Black (1997)']
["Marvin's Room (1996)"]
The common Movie in Recom & User: []


In [102]:
Recommended_movie=userbased(34,user_similarity,user_pred,5,1.5)

['I.Q. (1994)']
['Dances with Wolves (1990)']
['Snow White and the Seven Dwarfs (1937)']
['Spitfire Grill, The (1996)']
['Princess Bride, The (1987)']
['Apocalypse Now (1979)']
['Men in Black (1997)']
["Marvin's Room (1996)"]
The common Movie in Recom & User: []
